### ISSUE TITLE
Full screen ViewPager

### ISSUE THREAD

**Issue by fahimk** [zbtang/React-Native-ViewPager#1]
Thanks for sharing this component! Right now setting flex:1 on the ViewPager doesn't make it fill the screen, seems like it needs a specific number. Would be great if it could handle that.

**Comment by zbtang** [comment]
Sorry for no reply for a long time. What is your react-native version?
I try to set flex:1, and it works.
Here are my test code:
```
'use strict';
import React, {Component} from 'react';
import {StyleSheet, View,} from 'react-native';
import {ViewPager} from 'rn-viewpager'
export default class FullScreenPagerTest extends Component {
    static propTypes = {
        ...View.propTypes
    };
    static defaultProps = {};

    render() {
        return (
            <ViewPager style={{flex:1}}>
                <View style={{backgroundColor:'blue'}}/>
                <View style={{backgroundColor:'green'}}/>
                <View style={{backgroundColor:'yellow'}}/>
            </ViewPager>
        );
    }
}
```
Could you paste your code here? Maybe some parent node of ViewPager not set flex:1 or has no specific size.
