### ISSUE TITLE
ViewPager Inside ViewPager

### ISSUE THREAD

**Issue by c0d3blooded** [zbtang/React-Native-ViewPager#113]
Hi,

Thank you for this fantastic library. It's been very handy so far. Unfortunately, I've run into an issue with nested ViewPagers. A ViewPager inside another ViewPager has the indicators show up ok but the inner ViewPager's views aren't visible. 

I've tried a number of different flex and height values on the different elements and sections with no luck.

For more context, I'm using RN version 0.51.0 along with a tab based app in react-native-navigation. Here's an example:

```
            <View style={{flex :1}}>
                <Text>Header</Text>
                <IndicatorViewPager
                    style={{flex :1, flexDirection: 'column-reverse'}}
                    indicator={<PagerTitleIndicator
                        titles={['Tab 1', 'Tab 2']}
                        itemStyle={{width:windowWidth/2}}
                        selectedItemStyle={{width:windowWidth/2}}
                    />}
                >
                    <View>
                        <IndicatorViewPager
                            style={{flex :1, flexDirection: 'column-reverse'}}
                            indicator={<PagerTitleIndicator
                                titles={['Tab 3', 'Tab 4']}
                                itemStyle={{width:windowWidth/2}}
                                selectedItemStyle={{width:windowWidth/2}}
                            />}
                        >
                            <View style={{backgroundColor: '#a1a1a1'}}>
                                <Text>View Inner 1</Text>
                            </View>
                            <View style={{backgroundColor: '#a1a1a1'}}>
                                <Text>View Inner 2</Text>
                            </View>
                        </IndicatorViewPager>
                    </View>
                    <View style={{backgroundColor: '#ffffff'}}>
                        <Text>View 2</Text>
                    </View>
                </IndicatorViewPager>
            </View>
```

EDIT: I've also noticed that this is only an issue on Android. It looks like iOS works ok.

**Comment by c0d3blooded** [comment]
Looks like this is an issue with the RN ViewPagerAndroid component rather than the library (https://github.com/facebook/react-native/issues/12845). Setting forceScrollView=true is working for now.

**Comment by MSchmidt** [comment]
Where do you set `forceScrollView=true`?

**Comment by tyforcode** [comment]
I set it as an attribute in the for the IndicatorViewPager for example:

`                
<IndicatorViewPager
                    ref={(r) => this.viewPagerHistory = r}
                    style={styles.viewPager}
                    indicator={this._renderTitleIndicator()}
                    scrollEnabled={false}
                    horizontalScroll={false}
                    forceScrollView={true}>
`
