### ISSUE TITLE
大神,安卓闪退

### ISSUE THREAD

**Issue by cham1985** [zbtang/React-Native-ViewPager#12]
![bf35b014-d1b5-4993-8585-70074fa0d89b](https://cloud.githubusercontent.com/assets/7087874/17324021/03bd5432-58d7-11e6-81a8-3f5bb9a43af5.png)  少了 com.zubintang/com.zubintang.MainActivity目录啊
导致 安卓 闪退啊,

**Comment by zbtang** [comment]
谢谢，忘了提交文件，已经fix。
