### ISSUE TITLE
Android - setPage does not always work

### ISSUE THREAD

**Issue by dancomanlive** [zbtang/React-Native-ViewPager#123]
```
nextPage = (index) => {
      if (this.viewpager) {
        this.viewpager.setPage(index);
      }
    }


return (
          <View style={{ flex: 1 }}>
            <IndicatorViewPager
              ref={viewpager => this.viewpager = viewpager}
              style={{ height }}
            >
              {pages}
            </IndicatorViewPager>
          </View>
        );
```
{pages} is an array of Views

nextPage() is invoked inside onPress from TouchableOpacity

Running through the debugger there is no difference between when the page change is working and when it is not working. Sometimes it happens at random and there is one button among all the pages that doesn't change the page 99% of the time.

**Comment by MarkOSullivan94** [comment]
Yeah I'm experiencing a similar issue. I've done some testing and initialPage works fine the first time the IndicatorViewPager is rendered but every time after that it doesn't seem to update.
