### ISSUE TITLE
React-Native-ViewPager inside StackNavigator

### ISSUE THREAD

**Issue by Amir-P** [zbtang/React-Native-ViewPager#141]
I'm using React-Native-ViewPager with ReactNavigation and I wrapped my component inside a StackNavigator. Everything is fine but when I'm trying to scroll back on iOS if I'm on other pages than first page, the previous page appears on behind the component. here is my dependencies

    "react": "16.3.1",
    "react-native": "0.55.4",
    "rn-viewpager": "^1.2.9"
    "react-navigation": "^2.0.1",

and here is my JSX code

```
<View style={{flex: 1}}>
    <IndicatorViewPager
        style={{
            removeClippedSubviews: 'false',
            flex: 1,
            flexDirection: 'column-reverse',
            backgroundColor: 'white',
            width: Dimensions.get('window').width,
        }}
        removeClippedSubviews={false}
        indicator={this._renderTabIndicator()}>
        <View style={{overflow: 'hidden', backgroundColor: 'cadetblue'}}>
            <Text>page one</Text>
        </View>
        <View style={{overflow: 'hidden', backgroundColor: 'cornflowerblue'}}>
            <Text>page two</Text>
        </View>
        <View style={{overflow: 'hidden', backgroundColor: '#1AA094'}}>
            <Text>page three</Text>
        </View>
    </IndicatorViewPager>
</View>
```
How can I fix it?
<img width="433" alt="screen shot 2018-06-06 at 13 54 40" src="https://user-images.githubusercontent.com/8766492/41029623-5cefd26a-6991-11e8-82b4-29cbb8475f28.png">
<img width="436" alt="screen shot 2018-06-06 at 13 54 48" src="https://user-images.githubusercontent.com/8766492/41029624-5d21b8f2-6991-11e8-9979-5e199c239400.png">

**Comment by smn729** [comment]
try this style at your container: {overflow: "hidden"}
