### ISSUE TITLE
Change a page programmatically.

### ISSUE THREAD

**Issue by VlCTORlOUS** [zbtang/React-Native-ViewPager#16]
Hi!

Is it possible to programmatically change the page.
I want to change the page when a button is pressed.

Thanks in advance.

**Comment by zbtang** [comment]
You can call `pager. setPage(selectedPageIndex)` or `pager.setPageWithoutAnimation(selectedPageIndex)`

**Comment by Drey23** [comment]
"You can call pager. setPage(selectedPageIndex) or pager.setPageWithoutAnimation(selectedPageIndex)" This is not working. I got this error: "undefined is not an object (evaluating 'this.viewPager.setPage')" .


This is the code: 

`import React, { Component } from 'react';
import { View, TouchableWithoutFeedback } from 'react-native';
import { IndicatorViewPager } from 'rn-viewpager';
import { IntroOne, IntroTwo } from '@scenes/shared/Intros';

// Styles
import Styles from './styles';

export default class IntroPager extends Component {
  constructor () {
    super();
    this.state = {page : 0};
  }

  render () {
    return (
      <View style={Styles.mainContainer}>
        <IndicatorViewPager ref={viewPager => { this.viewPager = viewPager; }} style={Styles.IndicatorViewPagerStyle}>
          <View style={Styles.viewsInsidePager}>
            <TouchableWithoutFeedback onPress={this.updatePage.bind(1)}>
              <View>
                <IntroOne />
              </View>
            </TouchableWithoutFeedback>
          </View>
          <View style={Styles.viewsInsidePager}>
            <IntroTwo />
          </View>
        </IndicatorViewPager>
      </View>
    );
  }

  updatePage (myPage) {
    this.viewPager.setPage(myPage);
  }
}
`

**Comment by k2glyph** [comment]
I am also block in this issues please help.

**Comment by Drey23** [comment]
@k2glyph You must call set the component name with ref="viewPager" not with ref='viewPager'. Double quotation marks, inside a class
