### ISSUE TITLE
How to get current page?

### ISSUE THREAD

**Issue by SteffenC** [zbtang/React-Native-ViewPager#19]
Is it possible to get the current displayed page ?

**Comment by jreziga** [comment]
The author doesn't seem to be available to update this repository, if you need that feature I made a fork available at https://www.npmjs.com/package/react-native-viewpager-enhanced

You'll be able to :

- Call method getCurrentPageIndex on IndicatorViewPager's ref

**Comment by SteffenC** [comment]
@jreziga Thanks.

**Comment by gonglong** [comment]
@jr-k "npm install --save rn-viewpager" still install zbtang's than yours

**Comment by jr-k** [comment]
@gonglong you've to use "npm install --save react-native-viewpager-enhanced" instead.

**Comment by gonglong** [comment]
@jr-k Thank you. I think you'd better  update the document. 
![image](https://cloud.githubusercontent.com/assets/6356416/21412909/a6740592-c82e-11e6-94d4-b41a8ad70a48.png)

**Comment by MattyK14** [comment]
`getCurrentPageIndex()` doesn't work on your fork

**Comment by maartenvandillen** [comment]
you can also just use the onPageSelected property, it is called after the current page changes.

**Comment by mensonones** [comment]
```js
  onPageSelected={ pageSelected => {
    // pageSelected return  position
 }} 
 ```
