### ISSUE TITLE
Can I pass a method to be notified when the selected slide changes?

### ISSUE THREAD

**Issue by jorfermo** [zbtang/React-Native-ViewPager#20]
Can I pass a method to be notified when the selected slide changes?

**Comment by jreziga** [comment]
The author doesn't seem to be available to update this repository, if you need that feature I made a fork available at https://www.npmjs.com/package/react-native-viewpager-enhanced

You'll be able to :

- Listen event onItemPress on PagerTabIndicator and PagerTitleIndicator
- Listen event onPageChange on PagerTabIndicator, PagerTitleIndicator and PagerDotIndicator

**Comment by jorfermo** [comment]
Thanks!!

**Comment by KinanKazmi** [comment]
@jr-k 
Are you still managing your fork?
I have an addition to make, could you do a quick update?

**Comment by jr-k** [comment]
@KinanKazmi Yes I am. You can make a PR here: https://github.com/jr-k/React-Native-ViewPager

**Comment by KinanKazmi** [comment]
I cant do that from where i am atm.
Maybe you could do that?

In both PagerTitleIndicator.js AND PagerTabIndicator.js you have TouchableOpacity, which is the tab that you tap to move to that specific View ( screen or page ).
Just add in its props
`disabled = {this.props.disabled}'
That way, the user can make the tabs disabled, when needed.

**Comment by jr-k** [comment]
@KinanKazmi done

**Comment by KinanKazmi** [comment]
@jr-k
Thanks!

**Comment by jr-k** [comment]
@KinanKazmi Don't forget to npm update, the latest version is 1.1.11

**Comment by KinanKazmi** [comment]
@jr-k
Yup, already at it. Thanks.
