### ISSUE TITLE
Support for disabling scroll

### ISSUE THREAD

**Issue by elliotstokes** [zbtang/React-Native-ViewPager#31]
I was investigating using this pager as a wizard. As such I dont want the user to be able to manually swipe to the next page until all the information is complete. Is there a way in which I can disable scroll?

Looking at the code it seems like its always enabled and no way to disable.

Thanks

**Comment by zbtang** [comment]
Yes, you can just set props `scrollEnabled={false}` to disable scroll . Thanks !
