### ISSUE TITLE
pagingEnabled for android is supported since 0.28

### ISSUE THREAD

**Issue by braco** [zbtang/React-Native-ViewPager#34]
Assuming this was the original reason to create this package, it looks like pagingEnabled/horizontal is supported in Android now

`<ScrollView pagingEnabled={true}>`

Is the main reason to use this library for paging controls? Why use ViewPagerAndroid at all? That would be a helpful addition to the docs.

**Comment by zbtang** [comment]
ViewPagerAndroid in android platform is good for view recycle, so I use ViewPagerAndroid in android platform. Thanks!

**Comment by braco** [comment]
Thanks for the reply, @zbtang, I appreciate your work.

**Comment by zbtang** [comment]
Very happy with its usefulness to you!
