### ISSUE TITLE
Can this library Support Vertical Page Transistions

### ISSUE THREAD

**Issue by kalisjr** [zbtang/React-Native-ViewPager#35]
I have a need for a view-pager which supports all XML layout types, can infinitely scroll, overcome the Samsung lag issue with image sizing, can do page by page transitions via normal swipes but also enable a user to be able to dynamically increase the speed of the page transitions (velocity) via faster swiping. Currently a user swipes fast and the speed at which the page swap occurs is fixed at the same speed regardless of the speed at which they induce motion. 

The velocity requirement is calling for a viewpager that handles rapid swipes without inducing lag, stutter or jank when a user wants to continuously swipe fast to get to the page of interest within the page pool. 

The view pager should be able to handle 86 small images per page which includes the background and primary drawable resource. A viewpager which allows for each page to remain in RAM so it performs smooth and never degrades overtime. Also the viewpager must support ToxicBakery/ViewPagerTransforms. The viewpager delivers a true infinite scroll in horizontal and vertical motion events. Can this library do all of these things?

The project I need this for is calling for support of close to 90 images which do not change with drawable resources that reside local on disk. over 5 pages which should repeat when the end of page is reached. My project will use the ToxicBakery/ViewPagerTransforms to give user the ability to change the effect each page transition delivers.

I've read some impressive things about this library but didn't see support for vertical and as Nougat has a vertical app drawer this viewpager is becoming more popular over just the horizontal effect. 

I'd be willing to pay you to make the needed modifications to improve this library if you're open to it so long as the finished product has zero lag, stutter or jank as the user experience is every important to my project and has no tolerance for lag or memory leaks what so ever. If payment for these changes is acceptable please let me know how I can hire you and provide a quote on costs for these modifications.

Then others who have similar requirements for their projects can benefit from the enhancements.

Thanks

**Comment by zbtang** [comment]
Hello, sorry for no reply these time, because I'm just back from my vocation. Thanks for your attention first, and I am very happy my part-time work can help you. But in the next days I'll be a little busy on my major job, so I am afraid I have no enough time to focus on your requirement. So I am afraid it will delay you progress. But I will still implement your demands if I have time to make this library more perfect! Thanks!
