### ISSUE TITLE
How to change the size of dots?

### ISSUE THREAD

**Issue by mochamadArif** [zbtang/React-Native-ViewPager#36]

**Comment by MarkOSullivan94** [comment]
@mochamadArif not sure if you ever figured this out, if not, I've posted an example for you to follow.

As shown by the PagerDotIndicator API you can give a custom style for the default dot, selected dot, or both: https://github.com/zbtang/React-Native-ViewPager/blob/master/docs/dotindicator.md

Example:

```
const styles = StyleSheet.create({
  dotSelected: {
    height: 20,
    width: 20,
    borderRadius: 20 >> 1,
    margin: 20 >> 1,
    backgroundColor: '#000000',
    opacity: 0.5
  }
})
```

In this case your PagerDotIndicator object would look like the following:

`<PagerDotIndicator pageCount={5} selectedDotStyle={styles.dotSelected} />`
