### ISSUE TITLE
How to set current page?

### ISSUE THREAD

**Issue by cborjah** [zbtang/React-Native-ViewPager#37]
Is there a way to set the current page?

**Comment by zbtang** [comment]
Yes,  you can use the method `setPage(selectedPage)` of ViewPager or IndicatorViewPager's ref.

**Comment by vanbarneveld31** [comment]
Hi, I use setPage from componentwillReceiveProps when a certain property has changed. After setPage I reset a state property that forces a render again. 
`if (nextProps.expensesTabPage !== this.props.expensesTabPage) {
      this.viewPager.setPage(1);
      this.setState({ tabPage: nextProps.expensesTabPage });
    }`

` <IndicatorViewPager
            ref={(viewPager) => { this.viewPager = viewPager; }}
            style={styles.IndicatorViewPager}
            indicator={this.renderTitleIndicator()}
            onPageSelected={(event) => this.onPageSelectedTabs(event)}
            initialPage={this.state.tabpage}
          >
            <View>
              {this.renderExpenseList(this.state.dataSourceBooked.cloneWithRows(info.expensesBooked))}
            </View>
            <View>
              {this.renderExpenseList(this.state.dataSourceDrafts.cloneWithRows(info.expensesDrafts))}
            </View>
          </IndicatorViewPager>`

but I receive the error that setPage is not defined.
where and how can I use setPage?

**Comment by vanbarneveld31** [comment]
Correction: this works perfectly. Due to another flaw in my code I was confused.

**Comment by zbtang** [comment]
OK, very glad to help you. So I'll close this issue. Thanks!
