### ISSUE TITLE
Change page manually.

### ISSUE THREAD

**Issue by Drey23** [zbtang/React-Native-ViewPager#39]
"You can call pager. setPage(selectedPageIndex) or pager.setPageWithoutAnimation(selectedPageIndex)" This is not working. I got this error: "undefined is not an object (evaluating 'this.viewPager.setPage')" .

This is the code:
`import React, { Component } from 'react';
import { View, TouchableWithoutFeedback } from 'react-native';
import { IndicatorViewPager } from 'rn-viewpager';
import { IntroOne, IntroTwo } from '@scenes/shared/Intros';

// Styles
import Styles from './styles';

export default class IntroPager extends Component {
  constructor () {
    super();
    this.state = {page : 0};
  }

  render () {
    return (
      <View style={Styles.mainContainer}>
        <IndicatorViewPager ref={viewPager => { this.viewPager = viewPager; }} style={Styles.IndicatorViewPagerStyle}>
          <View style={Styles.viewsInsidePager}>
            <TouchableWithoutFeedback onPress={this.updatePage.bind(1)}>
              <View>
                <IntroOne />
              </View>
            </TouchableWithoutFeedback>
          </View>
          <View style={Styles.viewsInsidePager}>
            <IntroTwo />
          </View>
        </IndicatorViewPager>
      </View>
    );
  }

  updatePage (myPage) {
    this.refs.viewPager.setPage(myPage);
  }
}`

**Comment by zbtang** [comment]
Hi:
There something wrong in your `updatePage` method, it should be like below:
```
updatePage (myPage) {
        this.viewPager.setPage(myPage);
}
```
