### ISSUE TITLE
TouchableHighlight doesn't appear on the screen 

### ISSUE THREAD

**Issue by Luckygirlllll** [zbtang/React-Native-ViewPager#41]
When I'm trying to add TouchableHighlight on the any page of the ViewPager it doesn't render on the screen.

**Comment by zbtang** [comment]
Hi, could you show me some of your code to help me learn more about your situation. Thanks!

**Comment by Luckygirlllll** [comment]
Hi @zbtang, I have realized today, that it was a problem with styles in my code, so after the fixing it, the button has been rendered on the screen, so I will close this issue.
