### ISSUE TITLE
在ScrollView组件下嵌套IndicatorViewPager 想实现轮播图的效果，但不成功

### ISSUE THREAD

**Issue by doveq** [zbtang/React-Native-ViewPager#5]
你好， 页面可以显示，但是IndicatorViewPager不能切换页面，手势滑动没效果。不知有没有办法解决，谢谢。

**Comment by zbtang** [comment]
请问ScrollView有设置确定大小么？由于IndicatorViewPager 在iOS端是通过scrollView实现，所以IndicatorViewPager 必须要有一个确定的大小：直接指定width和height，或设置flex:1

**Comment by doveq** [comment]
谢谢，貌似是因为使用了 ScrollView 的下拉刷新功能导致手势被拦截了

**Comment by zbtang** [comment]
好的，那我关闭这个issue了哈
