### ISSUE TITLE
[iOS] onPageSelected firing twice

### ISSUE THREAD

**Issue by ericapply** [zbtang/React-Native-ViewPager#52]
Using `IndicatorViewPager` in iOS
`onPageSelected` callback is firing twice every page view.

versions
```
"rn-viewpager": "^1.1.4",
"react": "15.4.2",
"react-native": "0.41.2",
```

**Comment by masterpetit** [comment]
I encountered the same problem.

**Comment by zbtang** [comment]
Hello, I fix this bug just now.  Please upgrade `rn-viewpage` version to `1.2.2`. Thanks!

**Comment by masterpetit** [comment]
Thanks, works as expected now.

**Comment by ericapply** [comment]
My `onPageSelected` is still firing twice after upgrading to `1.2.2`

**Comment by YeshanJay** [comment]
Issue exists on Android now..
when `setPage` is called the `onPageSelected` event fires twice.
Once at `setPage`, and the other after the next page is viewed.
