### ISSUE TITLE
如何能支持滚出框的时候裁减掉view

### ISSUE THREAD

**Issue by RazerTang** [zbtang/React-Native-ViewPager#62]
我的IndicatorViewPager不是全屏的，向左滑的话第一页会滑出边框。如下图，能否提供一个思路来修改可以支持不是全屏的ViewPager.谢谢
![111](https://user-images.githubusercontent.com/5905640/27276474-e9626490-550d-11e7-97a1-a6f1c77bdf99.png)

**Comment by zbtang** [comment]
参考这个属性：
![image](https://user-images.githubusercontent.com/2532942/27277364-945f7124-5510-11e7-9f01-41b2f678d236.png)

**Comment by RazerTang** [comment]
非常感谢，看到你前一条回复的，已经实现。也谢谢你提供了这么好的库。
