### ISSUE TITLE
animation slider gets slow on every slide at end before it sets the screen

### ISSUE THREAD

**Issue by Bipin206** [zbtang/React-Native-ViewPager#63]
i am using this library and its working fine but the only problem is its gets slow on every slide at the end before the data holds the screen its the slower.

**Comment by PeterLocas** [comment]
@Bipin206 how to fix it?

**Comment by Bipin206** [comment]
@PeterLocas manage everything in asynchronous .... make sure your main thread is almost free of heavy data loading , use android studio monitor to check if your frames are getting skipped .. mange it and you are good to go
