### ISSUE TITLE
Android环境下使用轮播图片,轮播时键盘收起

### ISSUE THREAD

**Issue by songhanlin** [zbtang/React-Native-ViewPager#74]
andorid环境下,当页面同时存在轮播图和输入框的时候,点击输入框,唤起键盘,当轮播动画触发时,键盘收起,导致无法持续输入文字

**Comment by zbtang** [comment]
跟你设置的键盘收起方式有关吧

**Comment by songhanlin** [comment]
@zbtang 很显然,我并没有设置过特殊的键盘收起方式,ios下是正常的,android下是不行的.假设1秒轮播图切换一张,则点击进入输入框唤起键盘,一秒后就会消失

**Comment by zbtang** [comment]
android端的实现是使用的RN原生的ViewPagerAndroid，所以你可以设置一下ScrollView的keyboardDismissMode试一下
