### ISSUE TITLE
android滑动问题

### ISSUE THREAD

**Issue by MrShui** [zbtang/React-Native-ViewPager#76]
![image](https://user-images.githubusercontent.com/22006785/28818047-9a616ff8-76dc-11e7-8eb7-cd6bdb7e0949.png)
如上Banner控件就是用的此库，在android环境下，如果父view设置了backgroundColor，就会出现划不动的现象。。

**Comment by zbtang** [comment]
你需要对banner设置下宽度或者设置`flex:1`
