### ISSUE TITLE
why not support render data 

### ISSUE THREAD

**Issue by shanghongshen001** [zbtang/React-Native-ViewPager#79]

**Comment by zbtang** [comment]
what do you mean `render data`?

**Comment by shanghongshen001** [comment]
like ListView dataSource

**Comment by shanghongshen001** [comment]
!!我以为你是外国人     我的意思是    支持数据源  渲染页面

**Comment by zbtang** [comment]
你可以`dataList.map`，把你的数据源map成组件嘛

**Comment by shanghongshen001** [comment]
但是 数据源100+的话  每次map 都是一个工程   性能无法接受

**Comment by zbtang** [comment]
可以再这个组件的基础上再封装一层

**Comment by shanghongshen001** [comment]
我尝试封装了 但是失败了   
封装的思路是   初始渲染3个child    以中间的作为显示的child   两边个缓存一个   每次翻页后从新刷新所有child   
但是重新刷新的思路是失败的    因为刷新后也无法往后翻页了
你有什么好的idea吗

**Comment by zbtang** [comment]
你是在做一个类似电子书的软件么？

**Comment by shanghongshen001** [comment]
我在做一个做题的app  题目切换的时候希望能有viewpager效果

**Comment by shanghongshen001** [comment]
比你这个项目星星多一点的项目支持datasource但是是一个很久没有维护的项目    性能很差

**Comment by zbtang** [comment]
我觉得你可以试一下FlatList，这个比较适合这种大数据量的，然后只用自己做个回弹的效果就好了

**Comment by shanghongshen001** [comment]
好的 thanks ,i will try
