### ISSUE TITLE
ViewPager does not work with react-native 0.47.2

### ISSUE THREAD

**Issue by RomanISWG** [zbtang/React-Native-ViewPager#81]
In iOS it doesn't ends manually swipes (just scrolling without to stop at pages), in Android I cannot swipe at all. setPage works fine on both platforms. I have tried to set scrollEnabled to true, no changes in Android. All has worked fine in react-native 0.44.3
Any ideas to solve this?

**Comment by pewh** [comment]
+1 same problem on Android

**Comment by pewh** [comment]
I can make it work by add `horizontalScroll={true}` :tada:

**Comment by RomanISWG** [comment]
Perfect @pewh, this works on iOS and Android 👍🏻

**Comment by zbtang** [comment]
Thanks @pewh , I'll add default props `horizontalScroll={true}` to it.
