### ISSUE TITLE
ViewPager Dismisses Android Keyboard if newly introduced on render

### ISSUE THREAD

**Issue by zolrath** [zbtang/React-Native-ViewPager#85]
Hi!
I'm trying to use the ViewPager to allow users to search and select categories.

The IndicatorViewPager is only displayed when there are search results, and on iOS this works perfectly fine.

However, on Android this causes the keyboard to be dismissed and the Input to lose focus immediately after the first search characters are entered and the ViewPager is rendered.

Effectively, if the ViewPager is only rendered when there is text being entered:  
`{searchString ? this._renderViewPager() : null}`  
then it removes the Keyboard as the user beings typing.

**Comment by zolrath** [comment]
This also seems to happen if I replace the pages contained within the ViewPager and change its key to ensure it rerenders.

**Comment by zbtang** [comment]
Did you set `keyboadDismissMode` props on some ScrollView ?

**Comment by zolrath** [comment]
There is a ScrollView with these props:
```
        <ScrollView
          style={styles.container}
          keyboardDismissMode="interactive"
          keyboardShouldPersistTaps="handled"
        >
```
which provide the proper interaction on iOS.

**Comment by zbtang** [comment]
May be you can remove `keyboadDismissMode` props on android platform, if there is no need on Android platform. On android platform, this lib just directly use [ViewPagerAndroid](https://facebook.github.io/react-native/docs/viewpagerandroid.html) component , so maybe ReactNative itself mistaken the scroll event of ViewPagerAndroid .

**Comment by zolrath** [comment]
With the props removed the same issue still occurs. 
I can change the displayed views all I want but once it decides to render that ViewPagerAndroid the keyboard is immediately dismissed.

**Comment by zbtang** [comment]
Would you mind paste a screenshot of your app?

**Comment by zolrath** [comment]
![Gif of issue](https://media.giphy.com/media/l1J9yq74WBlp8QbXa/giphy.gif)

In the gif we start off with a `ViewPager` on screen, as we start to search it renders a simple `View` with text telling you to type more characters. Once they've typed two characters it renders a `ViewPager` with the results. Right as the `ViewPager` renders the Keyboard is dismissed. As we delete the search and return to 0 characters entered the search `View` is removed and the original `ViewPager` returns to the screen, dismissing the Keyboard.

**Comment by zbtang** [comment]
what it would be if keep an empty ViewPager node and do not remove when you start to search ? You can have a try.

**Comment by zolrath** [comment]
I just tried keeping just the Search ViewPager in view and I don't think its the ViewPager itself mounting that causes the keyboard dismissal but something about it performs its layout of pages, which happens when its first mounted as well as if the number of pages changes.

If we pass dynamic results into the ViewPager:

```
let content = (<View key={1}><Text>Page 1</Text></View>)
<ViewPager>
   {content}
<ViewPager>
```
and content returns two pages at a later render  
`content = [1,2].map(pageNum => <View key={pageNum}><Text>Page {pageNum}</Text></View>`

while changing to be a two page ViewPager the keyboard is dismissed.

**Comment by zbtang** [comment]
Sorry, just back from a business trip. There is ugly solution. You can add a Keyboard listener, and when      keyboard dismiss, pull it up manually.

**Comment by whysetiawan** [comment]
Add this:
`<IndicatorViewPager keyboardDismissMode='none'`
